import { DebateTableData } from './type';

export const DATETIME_FORMAT: string = 'yyyy-MM-dd HH:mm:ss';

export const OPEN_DEBATE_MAIN_ROUND: DebateTableData = {
  info: {
    id: '1-1-1-1-1',
    agenda: '국민연금 의무 가입을 폐지하여야 한다',
    datetime: '',
    name: '열린토론대회 예선 · 본선',
    prosTeamName: '찬성',
    consTeamName: '반대',
    finishBell: true,
    warningBell: false,
  },
  table: [
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 시작 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 시작 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '주도권 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 300,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '시간 총량제 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 300,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 마무리 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 마무리 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
  ],
} as const;

export const OPEN_DEBATE_FINAL_ROUND: DebateTableData = {
  info: {
    id: '1-1-1-1-1',
    agenda: '국민연금 의무 가입을 폐지하여야 한다',
    datetime: '',
    name: '열린토론대회 결선',
    prosTeamName: '찬성',
    consTeamName: '반대',
    finishBell: true,
    warningBell: false,
  },
  table: [
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 시작 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 시작 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '주도권 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 420,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '시간 총량제 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 420,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 마무리 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 마무리 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
  ],
} as const;
