import { DebateTableData } from '../type/type';

export const SAMPLE_TABLE_DATA: DebateTableData = {
  info: {
    id: '1-1-1-1-1',
    datetime: '',
    agenda: '나의 토론 주제',
    name: '나의 시간표',
    prosTeamName: '찬성',
    consTeamName: '반대',
    finishBell: true,
    warningBell: false,
  },
  table: [
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '입론',
      time: 180,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: '1번',
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '입론',
      time: 180,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: '1번',
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '반론',
      time: 180,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: '2번',
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반론',
      time: 180,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: '2번',
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '자유토론',
      time: null,
      timePerSpeaking: 120,
      timePerTeam: 420,
      speaker: '2번',
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '최종 발언',
      time: 180,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: '3번',
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '최종 발언',
      time: 180,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: '3번',
    },
  ],
} as const;

export const OPEN_DEBATE_MAIN_ROUND: DebateTableData = {
  info: {
    id: '1-1-1-1-1',
    datetime: '',
    agenda: '국민연금의 의무 가입을 폐지하여야 한다',
    name: '대한민국 열린토론대회 예선 · 본선',
    prosTeamName: '찬성',
    consTeamName: '반대',
    finishBell: true,
    warningBell: false,
  },
  table: [
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 시작 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 시작 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '주도권 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 300,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '시간 총량제 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 300,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 마무리 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 마무리 발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
  ],
} as const;

export const OPEN_DEBATE_FINAL_ROUND: DebateTableData = {
  info: {
    id: '1-1-1-1-1',
    datetime: '',
    agenda: '국민연금의 의무 가입을 폐지하여야 한다',
    name: '대한민국 열린토론대회 결선',
    prosTeamName: '찬성',
    consTeamName: '반대',
    finishBell: true,
    warningBell: false,
  },
  table: [
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 시작 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 시작 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '주도권 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 420,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '시간 총량제 토론',
      time: null,
      timePerSpeaking: null,
      timePerTeam: 420,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대 팀 마무리 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성 팀 마무리 발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
  ],
} as const;
