import { DebateTableData } from './type';

export const DATETIME_FORMAT: string = 'yyyy-MM-dd HH:mm:ss';

export const OPEN_DEBATE_MAIN_ROUND: DebateTableData = {
  info: {
    id: '1-1-1-1-1',
    agenda: '선거운동에 생성형 AI로 제작한 콘텐츠 사용을 전면 금지해야 한다',
    datetime: '',
    name: '열린토론대회 예선 · 본선',
    prosTeamName: '찬성',
    consTeamName: '반대',
    finishBell: false,
    warningBell: false,
  },
  table: [
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성팀 시작발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대팀 시작발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '시간 총량제',
      time: null,
      timePerSpeaking: 120,
      timePerTeam: 600,
      speaker: null,
      allowSpeakingOverflow: true,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대팀 마무리발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성팀 마무리발언',
      time: 90,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
  ],
} as const;

export const OPEN_DEBATE_FINAL_ROUND: DebateTableData = {
  info: {
    id: '1-1-1-1-1',
    agenda: '선거운동에 생성형 AI로 제작한 콘텐츠 사용을 전면 금지해야 한다',
    datetime: '',
    name: '열린토론대회 결선',
    prosTeamName: '찬성',
    consTeamName: '반대',
    finishBell: false,
    warningBell: false,
  },
  table: [
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성팀 시작발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대팀 시작발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'TIME_BASED',
      stance: 'NEUTRAL',
      speechType: '시간 총량제',
      time: null,
      timePerSpeaking: 120,
      timePerTeam: 840,
      speaker: null,
      allowSpeakingOverflow: true,
    },
    {
      boxType: 'NORMAL',
      stance: 'CONS',
      speechType: '반대팀 마무리발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
    {
      boxType: 'NORMAL',
      stance: 'PROS',
      speechType: '찬성팀 마무리발언',
      time: 120,
      timePerSpeaking: null,
      timePerTeam: null,
      speaker: null,
    },
  ],
} as const;
